export const IMAGES = [
    { name: "50 cent pointing1", src: "point.jpg", width: 2, height: 3, instagram: "", vero: "" },
    { name: "50 cent pointing2", src: "point.jpg", width: 1, height: 2, instagram: "", vero: "" },
    { name: "50 cent pointing3", src: "point.jpg", width: 3, height: 2, instagram: "" },
    { name: "50 cent pointing4", src: "point.jpg", width: 2, height: 4, vero: "" },
    { name: "50 cent pointing5", src: "point.jpg", width: 2, height: 3, instagram: "", vero: "" },
    { name: "50 cent pointing6", src: "point.jpg", width: 2, height: 3, instagram: "", vero: "" },
    { name: "50 cent pointing7", src: "point.jpg", width: 2, height: 2, instagram: "", vero: "" },
    { name: "50 cent pointing8", src: "point.jpg", width: 2, height: 1, instagram: "", vero: "" },
    { name: "50 cent pointing9", src: "point.jpg", width: 2, height: 1, instagram: "", vero: "" },
    { name: "50 cent pointing10", src: "point.jpg", width: 6, height: 6, instagram: "", vero: "" },
    { name: "50 cent pointing11", src: "point.jpg", width: 2, height: 3, instagram: "", vero: "" },
    { name: "50 cent pointing12", src: "point.jpg", width: 4, height: 4, instagram: "", vero: "" },
    { name: "50 cent pointing13", src: "point.jpg", width: 2, height: 5, instagram: "", vero: "" },
    { name: "50 cent pointing14", src: "point.jpg", width: 4, height: 4, instagram: "", vero: "" },
];