export const IMAGES = [
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 3, instagram: "", vero: "" },
    { name: "50 cent pointing", src: "point.jpg", width: 1, height: 2, instagram: "", vero: "" },
    { name: "50 cent pointing", src: "point.jpg", width: 3, height: 2, instagram: "" },
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 4, vero: "" },
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 3, instagram: "", vero: "" },
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 3, instagram: "", vero: "" },
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 2, instagram: "", vero: "" },
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 1, instagram: "", vero: "" },
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 1, instagram: "", vero: "" },
    { name: "50 cent pointing", src: "point.jpg", width: 6, height: 6, instagram: "", vero: "" },
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 3, instagram: "", vero: "" },
    { name: "50 cent pointing", src: "point.jpg", width: 4, height: 4, instagram: "", vero: "" },
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 5, instagram: "", vero: "" },
    { name: "50 cent pointing", src: "point.jpg", width: 4, height: 4, instagram: "", vero: "" },
];