export const IMAGES = [
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 3 },
    { name: "50 cent pointing", src: "point.jpg", width: 1, height: 2 },
    { name: "50 cent pointing", src: "point.jpg", width: 3, height: 2 },
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 4 },
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 3 },
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 3 },
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 2 },
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 1 },
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 1 },
    { name: "50 cent pointing", src: "point.jpg", width: 6, height: 6 },
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 3 },
    { name: "50 cent pointing", src: "point.jpg", width: 4, height: 4 },
    { name: "50 cent pointing", src: "point.jpg", width: 2, height: 5 },
    { name: "50 cent pointing", src: "point.jpg", width: 4, height: 4 },
];